<?php

/**
 * @file
 * Defines hooks and common functionality for the Entity Synchronization module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Hooks.
 */

/**
 * Implements hook_toolbar_alter().
 */
function entity_sync_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'entity_sync/toolbar';
}

/**
 * Implements hook_entity_insert().
 */
function entity_sync_entity_insert(EntityInterface $entity) {
  if (!$entity instanceof ContentEntityInterface) {
    return;
  }

  \Drupal::service('entity_sync.export.entity_manager')
    ->queueExportLocalEntityAllSyncs($entity);
}

/**
 * Implements hook_entity_update().
 */
function entity_sync_entity_update(EntityInterface $entity) {
  if (!$entity instanceof ContentEntityInterface) {
    return;
  }

  \Drupal::service('entity_sync.export.entity_manager')
    ->queueExportLocalEntityAllSyncs(
      $entity,
      ['context' => ['original_entity' => $entity->original]]
    );
}
